#PRINT TYPE OF EACH VARIABLE OF 5 DATA TYPES
name="Arjun"
address="Makaan no 3/12 krishna colony near kundan cinema, Jind, Haryana- 126102"
age=24
salary=50000.00
IS_STUDENT=False
c = 2 + 4j


print("Name:", name, "Type:", type(name))
print("Address:", address, "Type:", type(address))
print("Age:", age, "Type:", type(age))
print("Salary:", salary, "Type:", type(salary))
print("Is Student:", IS_STUDENT, "Type:", type(IS_STUDENT))
print("Complex Number:", c, "Type:", type(c))
