#WAP calculate  multiplication and division of two numbers and print the result
number1 = int(input("Enter first number: "))
number2 = int(input("Enter second number: "))
multiplication_result = number1 * number2
division_result = number1 / number2
print("The multiplication of", number1, "and", number2, "is:", multiplication_result)
print("The division of", number1, "by", number2, "is:", division_result)
